### ISSUE TITLE
Error when building using Java SDK 17

### ISSUE THREAD

**Issue by tobiaswjohn** [de-tu-dresden-inf-lat/lat-scala-dl-tools#1]
I tried to compile and publish with `mvn clean install`. Using SDK version 17 (17.0.11 to be specific), it produced the error shown below. Using Java SKD 11 (11.0.23) it works fine. I have not idea what the underlying issue is but if the tool can not be adapted to also work for Java SDK 17, it would be helpful to mention the supported / tested SDK versions in the readme.

```
[INFO] Reactor Summary for lat-scala-dl-tools_2.12 0.4.1-SNAPSHOT:
[INFO] 
[INFO] lat-scala-dl-tools_2.12 ............................ SUCCESS [  0.379 s]
[INFO] lat-scala-dl-tools-owlapi4_2.12 .................... FAILURE [  2.618 s]
[INFO] lat-scala-dl-tools-owlapi5_2.12 .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.076 s
[INFO] Finished at: 2024-07-16T18:56:20+02:00
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/share/maven/conf/logging/
constituent[1]: file:/usr/share/maven/lib/jsr250-api.jar
constituent[2]: file:/usr/share/maven/lib/maven-shared-utils.jar
constituent[3]: file:/usr/share/maven/lib/commons-lang3.jar
constituent[4]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[5]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[6]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[7]: file:/usr/share/maven/lib/maven-resolver-impl.jar
constituent[8]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[9]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[10]: file:/usr/share/maven/lib/maven-slf4j-provider-3.x.jar
constituent[11]: file:/usr/share/maven/lib/maven-resolver-connector-basic.jar
constituent[12]: file:/usr/share/maven/lib/maven-resolver-util.jar
constituent[13]: file:/usr/share/maven/lib/maven-resolver-provider-3.x.jar
constituent[14]: file:/usr/share/maven/lib/maven-resolver-api.jar
constituent[15]: file:/usr/share/maven/lib/jcl-over-slf4j.jar
constituent[16]: file:/usr/share/maven/lib/javax.inject.jar
constituent[17]: file:/usr/share/maven/lib/commons-io.jar
constituent[18]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[19]: file:/usr/share/maven/lib/guava.jar
constituent[20]: file:/usr/share/maven/lib/maven-resolver-transport-wagon.jar
constituent[21]: file:/usr/share/maven/lib/wagon-file.jar
constituent[22]: file:/usr/share/maven/lib/commons-cli.jar
constituent[23]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jar
constituent[24]: file:/usr/share/maven/lib/maven-builder-support-3.x.jar
constituent[25]: file:/usr/share/maven/lib/slf4j-api.jar
constituent[26]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[27]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[28]: file:/usr/share/maven/lib/jansi.jar
constituent[29]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[30]: file:/usr/share/maven/lib/maven-settings-3.x.jar
constituent[31]: file:/usr/share/maven/lib/sisu-plexus.jar
constituent[32]: file:/usr/share/maven/lib/maven-resolver-spi.jar
constituent[33]: file:/usr/share/maven/lib/aopalliance.jar
constituent[34]: file:/usr/share/maven/lib/wagon-http-shaded.jar
constituent[35]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[36]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[37]: file:/usr/share/maven/lib/cdi-api.jar
constituent[38]: file:/usr/share/maven/lib/guice-no-aop.jar
constituent[39]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[40]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
constituent[41]: file:/usr/share/maven/lib/sisu-inject.jar
constituent[42]: file:/usr/share/maven/lib/wagon-provider-api.jar
---------------------------------------------------
Exception in thread "main" java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
	at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:175)
	at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:55)
	at scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:66)
	at scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:65)
	at scala.tools.nsc.Global$$anon$1.findMacroClassLoader(Global.scala:448)
	at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:56)
	at scala.reflect.internal.SymbolTable$perRunCaches$$anon$1.apply(SymbolTable.scala:459)
	at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader(MacroRuntimes.scala:58)
	at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader$(MacroRuntimes.scala:58)
	at scala.tools.nsc.Global$$anon$1.defaultMacroClassloader(Global.scala:448)
	at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:76)
	at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:38)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:206)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:203)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:38)
	at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:31)
	at scala.tools.nsc.Global$$anon$1.standardMacroRuntime(Global.scala:448)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:448)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:445)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:445)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:445)
	at scala.tools.nsc.Global$$anon$1.pluginsMacroRuntime(Global.scala:448)
	at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:25)
	at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:25)
	at scala.tools.nsc.Global$$anon$1.macroRuntime(Global.scala:448)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:619)
	at scala.tools.nsc.Global.withInfoLevel(Global.scala:219)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:613)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:600)
	at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:764)
	at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:762)
	at scala.tools.nsc.Global$$anon$1.standardMacroExpand(Global.scala:448)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:432)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:429)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:429)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:429)
	at scala.tools.nsc.Global$$anon$1.pluginsMacroExpand(Global.scala:448)
	at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:757)
	at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:757)
	at scala.tools.nsc.Global$$anon$1.macroExpand(Global.scala:448)
	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1171)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1231)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5654)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2475)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$97(Typers.scala:5561)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:486)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5596)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5854)
	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2306)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5551)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5602)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2006)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1829)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5552)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5602)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5262)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5555)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5602)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5699)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:104)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:95)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:95)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:95)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:168)
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:94)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:142)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:84)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:159)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:68)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:207)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:189)
	at com.google.code.sbt.compiler.sbt013.SBT013Compiler.performCompile(SBT013Compiler.java:136)
	at com.google.code.sbt.compiler.plugin.AbstractSBTCompileMojo.internalExecute(AbstractSBTCompileMojo.java:472)
	at com.google.code.sbt.compiler.plugin.SBTCompileMojo.internalExecute(SBTCompileMojo.java:105)
	at com.google.code.sbt.compiler.plugin.AbstractSBTCompileMojo.execute(AbstractSBTCompileMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.RuntimeException: /packages cannot be represented as URI
	... 174 more
```

**Comment by stefborg** [comment]
I think so far we tested it only with Java 8, but mention this only in the Evee README (https://github.com/de-tu-dresden-inf-lat/evee). The main reason it does not work with Java 17 is probably that we would have to use a more recent version of Scala (instead of 2.12).

**Comment by stefborg** [comment]
See [commit ](https://github.com/de-tu-dresden-inf-lat/lat-scala-dl-tools/commit/6a689d974a33cc2a55cb6bb089ccb64482e5c569)
